[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add the section below
[rpc_endpoints]
worldchain = "https://worldchain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
hedera = "https://testnet.hashio.io/api"

[etherscan]
worldchain = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.worlds.org/api" }